spring:
  application:
    name:
      auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
    livereload:
      enabled: true
app:
  jwt:
    secret-key: ${JWT_SECRET:change_this_in_production_use_env_variable}
    token-validity-in-seconds: 3600
    refresh-token-validity-in-seconds: 86400
