server:
  port: 8080

spring:
  application:
    name: weather-service
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
    livereload:
      enabled: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.weatherforecast: INFO
    org.springframework.web: INFO
    org.springframework.boot.devtools: INFO

openweathermap:
  api:
    key: ${OPENWEATHERMAP_API_KEY}
    base-url: http://api.openweathermap.org
