spring:
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO

grpc:
  client:
    auth-service:
      address: auth-service:6565
      negotiationType: plaintext
    weather-service:
      address: weather-service:6565
      negotiationType: plaintext
