services:
  weather-service:
    build:
      context: ..
      dockerfile: infrastucture/docker/dev/weather-service/Dockerfile
    container_name: weather-service
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    env_file:
      - ../services/weather-service/.env
    volumes:
      - ../services/weather-service:/app
      - ~/.m2:/root/.m2
    networks:
      - wfs-network
    restart: unless-stopped

networks:
  wfs-network:
    driver: bridge
